{% set name = "hpc" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/hpc/archive/{{ version }}.tar.gz
  sha256: c583d420b517d7b76516077615f0659e9a103848dc8bd03e48ba66d172ba8bb9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.12
    - pip
  run:
    - python >=3.12
    - numpy >=2.0.0
    - scipy >=1.13.1


test:
  imports:
    - hpc

about:
  home: https://github.com/Serapieum-of-alex/hpc
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: numpy utility package
  description: |
    Numpy utility package with various functionality to handling numpy array.
  dev_url: https://github.com/Serapieum-of-alex/hpc
  doc_url: https://hpc-utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
