{% set python_min = "3.11" %}
{% set name = "hpc" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/hpc/archive/{{ version }}.tar.gz
  sha256: 25d4fd005cbef708db18271e62e720f742439abe489ea2fde14038a2a23e01c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0


test:
  requires:
    - python {{ python_min }}
  imports:
    - hpc

about:
  home: https://github.com/Serapieum-of-alex/hpc
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: numpy utility package
  description: |
    Numpy utility package with various functionality to handling numpy array.
  dev_url: https://github.com/Serapieum-of-alex/hpc
  doc_url: https://hpc-utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
