{% set name = "hpc" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/hpc/archive/{{ version }}.tar.gz
  sha256: 8e30e8053a92f1d5c73d6516db0e2bc27270e770f09b51a5dacba00dd1e9c16a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip
  run:
    - python >=3.11
    - numpy ==1.25.2

test:
  imports:
    - hpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Serapieum-of-alex/hpc
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: numpy utility package
  description: |
    Numpy utility package with various functionality to handling numpy array.
  dev_url: https://github.com/Serapieum-of-alex/hpc
  doc_url: https://hpc-utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
