{% set name = "hpc" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/hpc/archive/{{ version }}.tar.gz
  sha256: 95b5a0f73c5c95ef8bcc5a88cefddcae508f2ee9ade70b9fc6603de7b72b81da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip
  run:
    - python >=3.11
    - numpy ==1.25.2

test:
  imports:
    - hpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Serapieum-of-alex/hpc
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: numpy utility package
  description: |
    Numpy utility package with various functionality to handling numpy array.
  dev_url: https://github.com/Serapieum-of-alex/hpc
  doc_url: https://hpc-utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
